codecov:
  branch: main
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 20%
    patch:
      default:
        informational: true
  precision: 2
  round: up
  range: "70...100"

parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true

ignore:
  - ".husky/"
  - "build/"
  - "dist/"
  - "coverage/"
  - "src/index.ts"
  - "src/index-standalone.ts"
  - "eslint.config.js"
  - "prettier.config.js"
  - "vite.config.js"
  - "vite.config.standalone.js"
